### ISSUE TITLE
query on adding GitHub files to VSC 

### ISSUE THREAD

**Issue by Vakash123** [Bharathgopal/M1_Teaching_Util#2]
Sir While I was trying to add GitHub files to Visual studio code (via clone method) it had been done for my first practice time. But while again I was trying to add files from Github to VSC, I was not able to see the clone option of adding my files to VSC. So what is the process of adding GitHub files to VSC after our GitHub account is added in VSC?

**Comment by dhruva8601** [comment]
Try downloading the Git software, that might help you resolve the issue.

> Sir While I was trying to add GitHub files to Visual studio code (via clone method) it had been done for my first practice time. But while again I was trying to add files from Github to VSC, I was not able to see the clone option of adding my files to VSC. So what is the process of adding GitHub files to VSC after our GitHub account is added in VSC?

**Comment by Bharathgopal** [comment]
The clone is required only once. 
Recurring updating files between remote and local repository happens through push and pull.
Push - local to Remote.
Pull - Remote to local
