### ISSUE TITLE
Query regarding renaming repository

### ISSUE THREAD

**Issue by chaitanyakiran20** [Bharathgopal/M1_Teaching_Util#4]
Sir, 
I have named my repository as M1_projectgoal_game earlier, then I came up with the name of the project and wanted to change the name to M1_abc_game, The change is only reflecting on git hub but not in my visual studio code, I even updated both using pull and push. Is there something that I have to do for my changes to reflect in VSC?

**Comment by Bharathgopal** [comment]
The old name might be still retained in local repo.
You can start from "git clone" and save it it other place in your local machine. 

Close this thread if you found the solution.
