### ISSUE TITLE
Regarding submission of Repository in Submitty 

### ISSUE THREAD

**Issue by omeeom** [Bharathgopal/M1_Teaching_Util#6]
Dear Sir,
We are getting this error while submitting (text file including the repository link inside the file) in submitty but the Due Date is 02/06/2022 @ 11:59 PM IST and Time Remaining: 02 hours 37 mins. Kindly Help

![Screenshot 2022-02-06 212559](https://user-images.githubusercontent.com/80105220/152689315-9bdededb-85af-42f8-9b5e-e6aea405e63e.jpg)

Error:
"Your active version was submitted 1 day after the deadline but you only have 5 remaining late days.
Your grade for this assignment will be recorded as a zero.

Contact your instructor if you believe that this is an error or that you should be granted a deadline extension."

**Comment by sumit242k** [comment]
Have you set your Timezone to (UTC+5:30)Asia/Kolkata before submitting?
