### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by varunkumar572** [Bharathgopal/M1_Teaching_Util#8]
I am using void functions for generating borders and and fruits for my snake game. Now please help me how to test the void functions in testing phase. I don't want to return any value from that functions because if I keep return functions it affects my snake game. Please help me sir.

**Comment by Bharathgopal** [comment]
You need to check the variables that are updated inside the called function.
You will have expected values that each variable should have after the function call is made and actual values after the function call is made. 
Now Compare them and see if they are as expected.
